# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 00:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jrello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jrello',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jrello',
            name='last_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='jrello',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jrello',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
