# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrello', '0002_auto_20160513_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jrello',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'High'), (2, 'Moderate'), (3, 'Low')], null=True),
        ),
    ]
